name: Next release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org/"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Install dependencies
        run: pnpm install
      - name: Set git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: npm version prerelease --preid=dev
      - name: Push
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push -o ci.skip
      - name: Publish Package
        run: pnpm publish --tag next --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Deploy notification
        if: always()
        uses: adamkdean/simple-slack-notify@master
        with:
          channel: "#deployments"
          status: ${{ job.status }}
          success_text: "Version (#${{ steps.package-version.outputs.current-version}}) von @lenne.tech/eslint-config wurde erfolgreich released."
          failure_text: "Release (#${{ steps.package-version.outputs.current-version}}) von @lenne.tech/eslint-config ist fehlgeschlagen."
          cancelled_text: "Release (#$${{ steps.package-version.outputs.current-version}}) von @lenne.tech/eslint-config wurde abgebrochen."
